### ISSUE TITLE
materialUI를 customize한 내용이 페이지를 옮겨다닐때, 적용되지 않는 버그

### ISSUE THREAD

**Issue by dong149** [Nexters/Rollingpaper_client#24]
![image](https://user-images.githubusercontent.com/46394221/89211397-b9913e80-d5fc-11ea-9e2c-a6729547cf1a.png)

예시 사진입니다.

**Comment by dong149** [comment]
일단 NoSsr이라는 것을 사용하여, Button은 해결한 상태입니다. 문제는 Layout 설정입니다.

**Comment by swimjiy** [comment]
완료한 이슈 close
