### ISSUE TITLE
content 한 개 삭제기능

### ISSUE THREAD

**Issue by dong149** [Nexters/Rollingpaper_client#67]
서버단에서 content 한 개 삭제기능 추가

**Comment by dong149** [comment]
현재, rollingService.js에  롤링페이퍼를 통째로 삭제하는 feature밖에 구현이 안되어있습니다.

**Comment by leeinae** [comment]
롤링페이퍼 전체 삭제는 구현 안 했어요! content 단위로만 삭제할 수 있게 했습니다
