### ISSUE TITLE
Cards 자연스럽게 만들기 

### ISSUE THREAD

**Issue by dong149** [Nexters/Rollingpaper_client#68]
글자 수에 따라 유동적으로 변하게 짜야하지 않을까 싶습니다.
위아래 정렬이 필요합니다.

**Comment by dong149** [comment]
sender/main.js 와 receiver/main.js

**Comment by swimjiy** [comment]
sender/editor.js 글씨 많아질 경우 깨지는 이슈도 같이 수정할게요.
