### ISSUE TITLE
카드 내용, 보내는 이 글자수 제한

### ISSUE THREAD

**Issue by swimjiy** [Nexters/Rollingpaper_client#75]
현재는 카드 내용이랑 보내는 이 작성할 때 글자수 제한이 없어 계속 쓸 수 있는데, 어느 정도 제한은 필요하다고 생각합니다.
몇 자로 제한할 것인지는 논의가 필요할 듯.

**Comment by swimjiy** [comment]
논의 결과 : 텍스트 200자, 보내는이 6자

**Comment by jaeseongDev** [comment]
[완료]
- 보내는 이 6자까지는 완료

[문제점]
- 롤링페이퍼 본문 200자 수정하려는데, <ContentEditable>에서 onChange Props에서 이벤트 인식이 안됨

**Comment by swimjiy** [comment]
굿굿
