### ISSUE TITLE
자잘한 이슈 

### ISSUE THREAD

**Issue by swimjiy** [Nexters/Rollingpaper_client#88]
- [x] editor에서 저장 완료하고 나서 바로 메인 화면으로 이동하는 기능. (있으면 좋겠어서)
- [x] editor 작성할 때 엔터 치면서 이것저것 쓰면 editor화면에서는 안나오는데, main 에서는 html태그가 붙은 채로 나타남. 이건 사진 첨부 하겠음.
- 아직 작업 안할거...
- 추가할만한 이슈 있으면 코멘트 달아주세요.

**Comment by jaeseongDev** [comment]
editor에서 저장 완료하고 나서 바로 메인 화면으로 이동하는 기능 [완료] -> feature/88에 push한 상태
